@hostname = http://127.0.0.1:5003/api/v1/user-students

# all
###
GET {{hostname}}?orderByCol=id&orderByAsc=true&show_active_data=true&paginate=10 HTTP/1.1

# get
###
GET {{hostname}}/1 HTTP/1.1

# store
###
POST  {{hostname}}/store HTTP/1.1
content-type: application/json
# Authorization: {{token}}

{
    "name": "Tamim",
    "email": "tamim@gamil.com",
    "phone_number": "01779876546",
    "image": "/assets/dashboard/images/avatar.png",
    "password": "1234",
    "parent_id":1
}
# update
###
POST {{hostname}}/update HTTP/1.1 
content-type: application/json

{
    "id": 1,
    "name": "Habib",
    "email": "habib@gamil.com",
    "phone_number": "01779876546",
    "password": "12345678",
    "image": "/assets/dashboard/images/avatar.png"
}